version: "3.3"

services:
  db:
    image: postgres:12.4
    container_name: shopping-list-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "shopping-list"
      POSTGRES_USER: "appUser"
      POSTGRES_PASSWORD: "qwerty"

